import React, { useEffect, useState } from 'react';
import { ArrowDown, ArrowDownRight, ArrowRight, ArrowUpRight, Check, Code2, Database, Github, GraduationCap, Mail, Menu, Moon, Sun, X, Linkedin, Terminal, BriefcaseBusiness, MapPin, Layers3, Cpu, ExternalLink } from 'lucide-react';
import { projects } from './data/projects';
import { profile } from './data/config';
import ProjectModal from './components/ProjectModal';
import Preview from './components/Previews';

const nav=[['Home','home'],['About','about'],['Skills','skills'],['Projects','projects'],['Experience','experience'],['Education','education'],['Contact','contact']];
const skills=[['Frontend',Code2,['HTML · Basic','CSS · Basic','JavaScript · Learning','React · Learning']],['Backend',Terminal,['Node.js · Learning','FastAPI · Learning','REST API · Learning']],['Programming',Cpu,['Java · Learning','C++ · Learning','Python · Learning']],['Database',Database,['SQL · Learning','MongoDB · Learning','SQLite · Learning']],['Tools',Layers3,['Git · Learning','GitHub · Learning','Postman · Learning','VS Code · Learning']]];
function Navbar({theme,setTheme,active}) { const[open,setOpen]=useState(false);return <header className="navbar"><a href="#home" className="wordmark"><span>&lt;/&gt;</span> Vishal Kumar</a><nav className={open?'nav-links open':'nav-links'}>{nav.map(([label,id])=><a key={id} className={active===id?'active':''} href={`#${id}`} onClick={()=>setOpen(false)}>{label}</a>)}</nav><div className="nav-actions"><button className="theme-btn" onClick={()=>setTheme(theme==='dark'?'light':'dark')} aria-label="Toggle color theme">{theme==='dark'?<Sun size={17}/>:<Moon size={17}/>}</button><button className="mobile-menu" onClick={()=>setOpen(!open)} aria-label="Toggle menu">{open?<X/>:<Menu/>}</button></div></header>}
function Workspace(){return <div className="workspace-wrap"><div className="workspace-glow"/><div className="workspace"><div className="editor-top"><div className="editor-dots"><i/><i/><i/></div><span>vishal.js</span><span className="editor-live"><i/> available</span></div><div className="editor-body"><div className="line-nos">01<br/>02<br/>03<br/>04<br/>05<br/>06<br/>07<br/>08<br/>09</div><pre><span className="code-purple">const</span> developer = {'{'}<br/>  name: <span className="code-green">"Vishal Kumar"</span>,<br/>  role: <span className="code-green">"Full Stack Developer"</span>,<br/>  skills: [<span className="code-green">"React"</span>,<br/>          <span className="code-green">"JavaScript"</span>,<br/>          <span className="code-green">"Python"</span>],<br/>  building: <span className="code-green">"for the web"</span><br/>{'}'};<br/><span className="code-comment">// curious by default ✳</span></pre></div><div className="editor-bottom"><span><span className="green-dot"/> JavaScript</span><span>UTF-8&nbsp;&nbsp; · &nbsp;&nbsp;Ln 09, Col 3</span></div></div><div className="hero-photo-card"><img src="/images/vishal-kumar.png" alt="Vishal Kumar"/><span><i/> Vishal Kumar</span></div><div className="float-card float-react"><span className="tech-icon react-icon">⚛</span><span>React<small>UI library</small></span></div><div className="float-card float-python"><span className="tech-icon python-icon">Py</span><span>Python<small>Learning</small></span></div><div className="float-card float-db"><Database size={17}/><span>Database<small>Data layer</small></span></div><div className="float-pill"><span className="green-dot"/> building something new</div><div className="workspace-orbit orbit-one"/><div className="workspace-orbit orbit-two"/></div>}
function ResumeLink({className,children}){const[message,setMessage]=useState('');const download=async event=>{event.preventDefault();setMessage('');try{const response=await fetch(profile.resume,{method:'HEAD'});if(!response.ok||!response.headers.get('content-type')?.includes('pdf')){setMessage('Resume PDF is not added yet. Add it at public/resume/Vishal_Kumar_Resume.pdf.');return}window.location.assign(profile.resume)}catch{setMessage('Resume PDF is not available yet. Add it at public/resume/Vishal_Kumar_Resume.pdf.')}};return <span className="resume-link-wrap"><a className={className} href={profile.resume} onClick={download}>{children}</a>{message&&<small className="resume-message" role="status">{message}</small>}</span>}
function Hero(){return <section className="hero section-shell" id="home"><div className="hero-copy"><div className="availability"><i/> AVAILABLE FOR INTERNSHIPS &amp; OPPORTUNITIES</div><div className="hero-overline">COMPUTER SCIENCE STUDENT <span>·</span> GAYA, INDIA</div><h1>Hi, I'm<br/>Vishal Kumar<span className="title-period">.</span></h1><div className="hero-subtitle">Computer Science Student<br/><em>Building for the Web.</em></div><p className="hero-description">I build responsive, interactive and user-friendly web applications using modern web technologies.</p><div className="hero-buttons"><a className="button button-primary" href="#projects">View Projects <ArrowRight size={16}/></a><a className="button button-secondary" href="#contact">Contact Me <ArrowUpRight size={15}/></a></div><ResumeLink className="resume-link"><ArrowDown size={14}/> Download Resume <span>PDF</span></ResumeLink></div><Workspace/><div className="hero-stats"><div><b>04<span>+</span></b><small>PERSONAL PROJECTS</small></div><div><b>CSE</b><small>COMPUTER SCIENCE</small></div><div><b>WEB</b><small>DEVELOPMENT FOCUS</small></div><div><b>ML</b><small>LEARNING &amp; PROJECTS</small></div></div><a href="#about" className="scroll-hint"><ArrowDownRight size={15}/> SCROLL TO EXPLORE</a></section>}
function SectionHeading({kicker,title,description}){return <div className="section-heading"><div><div className="eyebrow"><i/>{kicker}</div><h2>{title}</h2></div>{description&&<p>{description}</p>}</div>}
function About(){return <section className="content-section section-shell" id="about"><SectionHeading kicker="A LITTLE ABOUT ME" title={<>About <span>Me</span></>}/><div className="about-grid"><div className="profile-card"><div className="profile-card-top"><span className="profile-status"><i/> OPEN TO OPPORTUNITIES</span><span className="profile-menu">···</span></div><div className="profile-photo"><img src="/images/vishal-kumar.png" alt="Portrait of Vishal Kumar"/><i/></div><div className="profile-name">Vishal Kumar</div><div className="profile-role">Aspiring Full Stack Developer</div><div className="profile-place"><MapPin size={13}/> Gaya, Bihar, India</div><div className="profile-divider"/><div className="profile-terminal"><span>~/vishal <b>✳</b></span><p><i>→</i> Curious mind. Building for the web.</p></div><div className="profile-bottom"><span><GraduationCap size={15}/> CSE STUDENT</span><span>INDIA · IST</span></div></div><div className="about-copy"><div className="about-lead">Curious about how things work.<br/><em>Driven to build what’s next.</em></div><p>I’m a Computer Science Engineering student at Haridwar University, interested in building thoughtful digital experiences and learning how the web works end to end.</p><p>My interests span frontend development, JavaScript, backend systems, APIs, databases, data analytics, and machine learning. I enjoy making applications that feel clear, useful, and good to use.</p><div className="info-cards"><div><GraduationCap/><small>EDUCATION</small><b>B.Tech CSE</b></div><div><Layers3/><small>UNIVERSITY</small><b>Haridwar University</b></div><div><Code2/><small>FOCUS</small><b>Web Development</b></div><div><ArrowUpRight/><small>CAREER GOAL</small><b>Full Stack Developer</b></div></div></div></div></section>}
function Skills(){return <section className="content-section section-shell" id="skills"><SectionHeading kicker="WHAT I WORK WITH" title={<>Technical <span>Skills</span></>} description="A growing toolkit for building across the stack. I’m always learning and adding to it."/><div className="skills-grid">{skills.map(([title,Icon,items],idx)=><article className="skill-card" key={title}><div className="skill-card-head"><span className="skill-icon"><Icon size={18}/></span><span className="skill-index">0{idx+1}</span></div><h3>{title}</h3><div className="skill-list">{items.map((s,i)=><span key={s} className="skill-chip"><i className={`skill-dot dot-${i%3}`}/>{s.split(' · ')[0]}<small>{s.split(' · ')[1]}</small></span>)}</div></article>)}</div></section>}
function Projects({onOpen}){return <section className="content-section projects-section section-shell" id="projects"><SectionHeading kicker="SELECTED WORK" title={<>Featured <span>Projects</span></>} description="Some of the projects I've built while exploring web development, data analytics and machine learning."/><div className="projects-list">{projects.map((p,i)=><article className={`project-card project-${p.kind}`} key={p.id}><button className="project-preview-button" onClick={()=>onOpen(p)} aria-label={`View ${p.name} details`}><Preview kind={p.kind}/><span className="preview-overlay">VIEW PROJECT <ArrowUpRight size={14}/></span></button><div className="project-info"><div className="project-counter">0{i+1} <span> / {String(projects.length).padStart(2,'0')}</span></div><div className="project-title-row"><div><h3>{p.name}</h3><span className="project-subtitle">{p.subtitle}</span></div><button className="project-open" onClick={()=>onOpen(p)} aria-label={`Open ${p.name}`}><ArrowUpRight size={19}/></button></div><p className="project-description">{p.description}</p><div className="project-feature-list">{p.features.slice(0,4).map(f=><span key={f}><Check size={12}/>{f}</span>)}</div><div className="tag-list">{p.technologies.map(t=><span key={t}>{t}</span>)}</div><div className="project-links"><button onClick={()=>onOpen(p)}>Explore project <ArrowRight size={15}/></button>{p.github&&<a href={p.github} target="_blank" rel="noreferrer">GitHub <ArrowUpRight size={13}/></a>}{p.live&&<a href={p.live} target="_blank" rel="noreferrer">Live Demo <ArrowUpRight size={13}/></a>}</div></div></article>)}</div></section>}
function Experience(){return <section className="content-section section-shell" id="experience"><SectionHeading kicker="WHERE I’VE BEEN" title={<>Experience <span>&amp; Learning</span></>} description="Early in my journey and building experience through hands-on projects."/><div className="timeline"><div className="timeline-entry"><div className="timeline-marker"><BriefcaseBusiness size={16}/></div><div className="timeline-content"><div className="timeline-meta"><span>EXPERIENCE</span><span>OPEN TO OPPORTUNITIES</span></div><h3>Internship / Experience</h3><div className="timeline-company">Company name <span>·</span> Role / position</div><p>Details about responsibilities, contributions, and technologies can be added here.</p><div className="tag-list"><span>Duration: Add dates</span><span>Technologies: Add tools</span></div><span className="certificate-link">Certificate: Add link when available <ArrowUpRight size={13}/></span></div><div className="timeline-date">TO BE UPDATED</div></div><div className="timeline-entry"><div className="timeline-marker"><Code2 size={16}/></div><div className="timeline-content"><div className="timeline-meta"><span>PROJECT WORK</span><span>SELF DIRECTED</span></div><h3>Learning through building</h3><div className="timeline-company">Personal web &amp; data projects</div><p>Exploring frontend development, APIs, databases, data analytics, and machine learning through practical projects.</p><div className="tag-list"><span>Web development</span><span>Data analytics</span><span>Machine learning</span></div></div><div className="timeline-date">ONGOING</div></div></div></section>}
function Education(){return <section className="content-section education-section section-shell" id="education"><SectionHeading kicker="ACADEMIC BACKGROUND" title={<>Education<span>.</span></>}/><div className="education-card"><div className="education-icon"><GraduationCap size={24}/></div><div className="education-main"><span className="eyebrow">UNDERGRADUATE DEGREE</span><h3>B.Tech <span>in</span> Computer Science Engineering</h3><div className="education-school">Haridwar University</div><p>Building a strong foundation in computer science and software development.</p></div><div className="education-date"><span>DURATION</span><b>Add duration</b><small>Update when available</small></div><div className="education-decoration">B.Tech</div></div></section>}
function Resume(){return <section className="resume-banner section-shell"><div className="resume-mark"><Code2 size={22}/></div><div><div className="eyebrow">A QUICK INTRODUCTION</div><h2>Want to know more<br/>about <em>me?</em></h2><p>Download my resume to learn more about my education, skills, projects and experience.</p></div><ResumeLink className="button button-primary">Download Resume <ArrowDown size={16}/></ResumeLink><div className="resume-watermark">CV<span>.</span></div></section>}
function Contact(){
 const[status,setStatus]=useState('');
 const[sending,setSending]=useState(false);
 const submit=async e=>{
  e.preventDefault();
  const form=e.currentTarget;
  const d=new FormData(form);
  if(!profile.email){setStatus('Add your email in src/data/config.js to receive messages.');return}
  setSending(true);setStatus('Sending your message…');
  try{
   const response=await fetch('/api/contact',{
    method:'POST',headers:{'Content-Type':'application/json','Accept':'application/json'},
    body:JSON.stringify({name:d.get('name'),email:d.get('email'),subject:d.get('subject'),message:d.get('message'),website:d.get('website')})
   });
   const result=await response.json().catch(()=>({}));
   if(response.status===404)throw new Error('The contact email API is missing on this server. Restart the dev server or redeploy the latest site.');
   if(!response.ok||!result.success)throw new Error(result.message||`Email service returned ${response.status}.`);
   form.reset();setStatus('Message sent successfully. Thanks for reaching out!');
  }catch(error){
   const reason=error instanceof TypeError?'Could not reach the email server.':error instanceof Error?error.message:'Unknown email delivery error.';
   setStatus(`${reason} Please try again or email ${profile.email} directly.`);
  }
  finally{setSending(false)}
 };
 return <section className="content-section contact-section section-shell" id="contact"><SectionHeading kicker="LET’S CONNECT" title={<>Contact <span>Me</span></>}/><div className="contact-grid"><div className="contact-copy"><h3>Let's Build<br/><em>Something Together.</em></h3><p>Have an opportunity, internship or project in mind? Let's connect.</p><div className="contact-links">{[['GitHub',profile.github,Github],['LinkedIn',profile.linkedin,Linkedin],['Email',profile.email,Mail],['Gmail',profile.gmail,Mail]].map(([label,url,Icon])=><a key={label} href={url?label==='Email'?`mailto:${url}`:url:undefined} target={label==='Email'?undefined:'_blank'} rel="noreferrer" className={!url?'unconfigured':''}><span><Icon size={17}/></span><b>{label}</b><small>{label==='Gmail'?'Open Gmail':url||'Add your link'}</small>{url&&<ArrowUpRight size={14}/>}</a>)}</div></div><form className="contact-form" onSubmit={submit}><div className="form-heading"><span>DROP A MESSAGE</span><span className="form-status"><i/> I’LL GET BACK TO YOU</span></div><label className="honeypot" aria-hidden="true">Website<input name="website" tabIndex={-1} autoComplete="off"/></label><div className="form-row"><label>Your name<input name="name" placeholder="Jane Smith" required/></label><label>Email address<input type="email" name="email" placeholder="jane@example.com" required/></label></div><label>Subject<input name="subject" placeholder="What would you like to discuss?" required/></label><label>Message<textarea name="message" placeholder="Tell me a little about it..." rows="4" required/></label><button className="button button-primary" type="submit" disabled={sending}>{sending?'Sending…':'Send Message'} <ArrowUpRight size={16}/></button>{status&&<small className="form-status-message" role="status">{status}</small>}</form></div></section>
}function Footer(){return <footer className="footer section-shell"><a href="#home" className="wordmark"><span>&lt;/&gt;</span> Vishal Kumar</a><span className="footer-role">Aspiring Full Stack Developer</span><div className="footer-links">{[['GitHub',profile.github],['LinkedIn',profile.linkedin],['Email',profile.email]].map(([t,u])=>u&&<a key={t} href={t==='Email'?`mailto:${u}`:u} target={t==='Email'?undefined:'_blank'} rel="noreferrer">{t}</a>)}</div><small>© 2026 Vishal Kumar. All Rights Reserved.</small><a className="back-top" href="#home">BACK TO TOP ↑</a></footer>}
export default function App(){const[theme,setTheme]=useState(()=>localStorage.getItem('vk-theme')||'dark');const[active,setActive]=useState('home');const[selected,setSelected]=useState(null);useEffect(()=>{document.documentElement.dataset.theme=theme;localStorage.setItem('vk-theme',theme)},[theme]);useEffect(()=>{const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting)setActive(e.target.id)}),{rootMargin:'-30% 0px -60% 0px'});nav.forEach(([,id])=>{const el=document.getElementById(id);if(el)observer.observe(el)});return()=>observer.disconnect()},[]);useEffect(()=>{const els=document.querySelectorAll('.content-section, .resume-banner, .project-card, .skill-card, .hero-stats');if(!('IntersectionObserver' in window)){els.forEach(el=>el.classList.add('revealed'));return}const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('revealed');io.unobserve(e.target)}}),{threshold:.08});els.forEach(el=>{el.classList.add('reveal');io.observe(el)});return()=>io.disconnect()},[]);return <><div className="grid-background"/><Navbar theme={theme} setTheme={setTheme} active={active}/><main><Hero/><About/><Skills/><Projects onOpen={setSelected}/><Experience/><Education/><Resume/><Contact/></main><Footer/><ProjectModal project={selected} onClose={()=>setSelected(null)}/></>}
